name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build and deploy docs
    runs-on: ubuntu-18.04
    container: ubuntu:bionic
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y python3-pip libsecp256k1-dev
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
