name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build and deploy docs
    runs-on: ubuntu-20.04
    container: ubuntu:xenial
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          apt update
          apt install -y -q libsecp256k1-dev
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
